export enum Skills {
  FIRE_MAKING_1 = "Firemaking_1",
  FIRE_MAKING_2 = "Firemaking_2",
  FIRE_MAKING_3 = "Firemaking_3",
  FISHING_1 = "Fishing_1",
  FISHING_2 = "Fishing_2",
  FISHING_3 = "Fishing_3",
  COOKING_1 = "Cooking_1",
  COOKING_2 = "Cooking_2",
  COOKING_3 = "Cooking_3",
  WOODCUTTING_1 = "Woodcutting_1",
  WOODCUTTING_2 = "Woodcutting_2",
  WOODCUTTING_3 = "Woodcutting_3",
  BUILDING_1 = "Building_1",
  BUILDING_2 = "Building_2",
  BUILDING_3 = "Building_3",
}
