// Generated from DESIGN.md traits.
export const TRAITS: Record<string, string> = {
  "calm": "slow to anger or panic",
  "hot-tempered": "quick to anger and fight",
  "anxious": "sees danger everywhere, avoids risk",
  "brave": "faces danger head on",
  "cowardly": "flees or hides from danger",
  "melancholy": "often low, needs company or purpose",
  "cheerful": "lifts people around them",
  "moody": "swings between highs and lows",
  "patient": "happy with long, slow work",
  "impulsive": "acts first, thinks later",
  "stoic": "bears hardship without complaint",
  "excitable": "easily thrilled and distracted",
  "gregarious": "seeks crowds and company",
  "loner": "prefers to live and work alone",
  "shy": "slow to approach strangers",
  "charismatic": "others are drawn to them",
  "abrasive": "rubs people the wrong way",
  "loyal": "sticks with friends through trouble",
  "fickle": "changes allegiances easily",
  "trusting": "believes others by default",
  "suspicious": "assumes others want something",
  "protective": "guards the weak and their own",
  "jealous": "resents others' bonds and success",
  "forgiving": "lets grudges go",
  "vengeful": "never forgets a wrong",
  "flirtatious": "seeks romance",
  "gossip": "trades in rumors",
  "discreet": "keeps secrets",
  "peacemaker": "defuses fights between others",
  "domineering": "needs to be in charge",
  "deferential": "follows stronger personalities",
  "clannish": "favors kin and close friends over outsiders",
  "honest": "rarely lies",
  "deceitful": "lies when it helps",
  "generous": "shares freely",
  "greedy": "hoards and wants more",
  "just": "cares about fairness and rules",
  "ruthless": "does whatever works",
  "merciful": "spares enemies",
  "cruel": "enjoys others' pain",
  "pious": "devout, follows a faith",
  "cynical": "believes in nothing and no one",
  "honorable": "keeps promises at a cost",
  "opportunist": "takes any advantage",
  "humble": "plays down their own worth",
  "arrogant": "thinks they're better than others",
  "lawful": "respects authority",
  "rebellious": "resists authority",
  "selfless": "puts others' needs first",
  "selfish": "puts their own needs first",
  "ambitious": "wants power, wealth, or status",
  "content": "happy with what they have",
  "industrious": "always working",
  "lazy": "avoids effort when they can",
  "curious": "explores and experiments",
  "cautious": "sticks to the known",
  "competitive": "must win and be best",
  "perfectionist": "slow but excellent work",
  "restless": "can't stay in one place",
  "homebody": "attached to their home",
  "adventurous": "seeks danger and new places",
  "visionary": "dreams of what could be built",
  "pragmatic": "does what's needed now",
  "stubborn": "won't change course",
  "adaptable": "changes plans easily",
  "clever": "learns and solves problems fast",
  "dim": "slow to learn",
  "wise": "good judgment about people and life",
  "naive": "easily fooled",
  "scholarly": "loves books and learning",
  "practical": "learns by doing",
  "creative": "invents and makes art",
  "traditional": "does things the old way",
  "superstitious": "sees omens and curses",
  "skeptical": "needs proof",
  "absent-minded": "forgets tasks and items",
  "observant": "notices details and lies",
  "strategic": "plans many steps ahead",
  "dreamer": "head in the clouds",
  "glutton": "eats more than needed",
  "ascetic": "needs little food or comfort",
  "drunkard": "drawn to ale and wine",
  "hoarder": "keeps everything",
  "tidy": "keeps things in order",
  "slovenly": "lets things fall apart",
  "early riser": "up at dawn, sleeps early",
  "night owl": "active after dark",
  "thrifty": "saves for the future",
  "spendthrift": "spends as soon as they have",
  "vain": "cares about looks and status goods",
  "animal lover": "drawn to beasts, good with them",
  "nature lover": "prefers wild places to towns",
  "craftsperson at heart": "loves making things",
  "hardy": "rarely sick, tough in cold",
  "frail": "tires and sickens easily",
  "strong": "carries more, hits harder",
  "nimble": "quick and agile",
  "keen-eyed": "sees far",
  "touched by magic": "arcane skills come easily",
  "cursed": "bad luck follows them"
};
